#!/bin/bash

time ./motion-vector tests/PrestigiousEnchantedKusimanse-size_restricted_frame_0001.bmp tests/PrestigiousEnchantedKusimanse-size_restricted_frame_0021.bmp

time ./motion-vector tests/PrestigiousEnchantedKusimanse-size_restricted_frame_0002.bmp tests/PrestigiousEnchantedKusimanse-size_restricted_frame_0020.bmp

time ./motion-vector tests/PrestigiousEnchantedKusimanse-size_restricted_frame_0003.bmp tests/PrestigiousEnchantedKusimanse-size_restricted_frame_0019.bmp

time ./motion-vector tests/PrestigiousEnchantedKusimanse-size_restricted_frame_0004.bmp tests/PrestigiousEnchantedKusimanse-size_restricted_frame_0018.bmp
